### ISSUE TITLE
Feature request: IBM MQ support

### ISSUE THREAD

**Issue by OleksandrShkurat** [klyashko/jms-messenger#13]
I would be grateful for adding IBM MQ support

**Comment by klyashko** [comment]
Hi @OleksandrShkurat 
I was thinking about it but as I know a jar to work with IBM MQ is provided with it and according to it's license it's not allowed to use it without payment. And I don't know if there is a way to test it locally.
If you have any ideas how to solve the problems we can discuss that.

**Comment by OleksandrShkurat** [comment]
As an idea, I'd suggest searching the IBM MQ jar in the current project's classpath and in case of its availability to show up the optional tab in your plugin. It will allow to avoid including their jar into the plugin bundle and delegating all the questions regarding the JAR usage to the project and its owner. Talking about the local testing I can suggest myself for this activity. Our client use IBM MQ 8.0.0.4 and we've got the jar included into the project (the public Maven repository doesn't have this version)

**Comment by klyashko** [comment]
I'll check if it's possible to extend the plugin classpath. But I'll need that jar anyway at least for compilation.

**Comment by kazimirov999** [comment]
Hi, @klyashko do you have any progress with IBM MQ? Maybe you can provide a small guide on how to run this plugin for debugging from IDEA then I will be able to help with the implementation.

**Comment by klyashko** [comment]
Hi @kazimirov999. I don't due to I don't have a jar which is required for this implementation.
If you can share it it may help, if not, I can think about how to approach the situation for you if you want to help with implementation.

**Comment by kazimirov999** [comment]
Hi @klyashko. Thank you for replying. I am not sure I understand what JAR do you mean.
To work with IBM MQ from Java there are _IBM MQ classes jar and JMS_  they are free - https://mvnrepository.com/artifact/com.ibm.mq/com.ibm.mq.allclient/9.2.4.0
To have IBM MQ up and running this docker-compose can be used:
```
version: "3"

services:
  ibmmq:
    image: ibmcom/mq:latest
    ports:
      - "9443:9443"
      - "1414:1414"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=MQA01
      - MQ_ADMIN_PASSWORD=admin
      - MQ_APP_PASSWORD=admin
    stdin_open: true
    tty: true
    restart: always
    volumes:
        - ~/.docker-conf/ibmmq/data/:/var/lib/ibmmq/
        - ~/.docker-conf/ibmmq/log/:/var/log/ibmmq
    networks:
        - ibmmq_go_net

networks:
  ibmmq_go_net:
    external: false
    name: ibmmq_network
```
Also, there is a short example of how to work with IBM MQ from Java -
https://developer.ibm.com/tutorials/mq-develop-mq-jms/
I'd gladly help you but I spent a day and was not able to run the code from IDEA
